base_path = "/Users/brianmodel/Downloads/130000_Pop_Rock_Classical_Videogame_EDM_MIDI_Archive[6_19_15]/"
note_mapping = {
    "C": 0,
    "C#": 1,
    "D-": 1,
    "D": 2,
    "D#": 3,
    "E-": 3,
    "E": 4,
    "F-": 4,
    "E#": 5,
    "F": 5,
    "F#": 6,
    "G-": 6,
    "G": 7,
    "G#": 8,
    "A-": 8,
    "A": 9,
    "A#": 10,
    "B-": 10,
    "B": 11,
    "B#": 0,
    "C-": 11,
}
