from os.path import dirname, abspath, join
import torch

base_path = dirname(dirname(abspath(__file__)))
data_path = join(dirname(dirname(abspath(__file__))), "data")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Mapping of instruments to eliminate redundencies
# All unique instruments:
# {'Trumpet', 'BassClarinet', 'Flute', 'Trombone', 'Violin',
# 'Oboe', 'Bassoon', 'Harp', 'DoubleBass', 'Clarinet', 'Cello',
# 'Tuba', 'Percussion', 'Viola', 'Horn'}

inst_mapping = {
    "Flute2.h5": "Flute",
    "Horn4.h5": "Horn",
    "Harp1.h5": "Harp",
    "DoublebassSolo1.h5": "DoubleBass",
    "Cellosolo2.h5": "Cello",
    "Oboe1.h5": "Oboe",
    "Bassoon3.h5": "Bassoon",
    "Trombone1.h5": "Trombone",
    "Bassoon2.h5": "Bassoon",
    "Horn1.h5": "Horn",
    "Flute3.h5": "Flute",
    "Trumpet1.h5": "Trumpet",
    "DoublebassTutti.h5": "DoubleBass",
    "DoublebassSolo.h5": "DoubleBass",
    "Cellib.h5": "Cello",
    "ViolinITutti.h5": "Violin",
    "ViolaTutti.h5": "Viola",
    "ViolinsIITutti.h5": "Violin",
    "ClarinetBass1.h5": "BassClarinet",
    "ViolinsIIb.h5": "Violin",
    "Tuba1.h5": "Tuba",
    "ViolinIIsolo2.h5": "Violin",
    "BassTrb(TubaMB).h5": "Tuba",
    "ViolaSolo1.h5": "Viola",
    "Percussion1.h5": "Percussion",
    "ViolinIsolo.h5": "Violin",
    "Piccolo1.h5": "Flute",
    "ViolinIsolo1.h5": "Violin",
    "Percussion49.h5": "Percussion",
    "ViolinIIsolo.h5": "Violin",
    "Timpani(Hn5Full).h5": "Percussion",
    "Tuba1(HarpMB).h5": "Tuba",
    "ViolinsIb.h5": "Violin",
    "CelliTutti.h5": "Cello",
    "Clarinet2(Bb).h5": "Clarinet",
    "Tuba.h5": "Tuba",
    "ViolinsITutti.h5": "Violin",
    "BassClarinet(Cl3MB).h5": "BassClarinet",
    "ViolaSolo2.h5": "Viola",
    "Percussion2.h5": "Percussion",
    "Timpani1.h5": "Percussion",
    "ClarinetinBb1.h5": "Clarinet",
    "ViolinIsolo2.h5": "Violin",
    "BassoonContra1.h5": "Bassoon",
    "Piccolo.h5": "Flute",
    "ViolinIITutti.h5": "Violin",
    "FlutePicc1.h5": "Flute",
    "Tuba2.h5": "Tuba",
    "TromboneBass.h5": "Trombone",
    "Violab.h5": "Viola",
    "ViolinIIsolo1.h5": "Violin",
    "EnglishHorn.h5": "Horn",
    "Trombone2.h5": "Trombone",
    "Percussion50.h5": "Percussion",
    "Oboe3.h5": "Oboe",
    "Bassoon1.h5": "Bassoon",
    "Horn2.h5": "Horn",
    "BassClarinet.h5": "BassClarinet",
    "Trumpet2.h5": "Trumpet",
    "CelloTutti.h5": "Cello",
    "Clarinet1(Bb).h5": "Clarinet",
    "Flute1.h5": "Flute",
    "Trumpet3.h5": "Trumpet",
    "Clarinet3(Bb).h5": "Clarinet",
    "BassTrombone.h5": "Trombone",
    "Harp2.h5": "Harp",
    "Cellosolo1.h5": "Cello",
    "Trombone3.h5": "Trombone",
    "Oboe2.h5": "Oboe",
    "Contrabassoon.h5": "DoubleBass",
    "Horn3.h5": "Horn",
}
