from os.path import dirname, abspath, join
import torch

base_path = dirname(dirname(abspath(__file__)))
data_path = join(dirname(dirname(abspath(__file__))), "data")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Mapping of instruments to eliminate redundencies
# All unique instruments:
instruments = [
    "Trumpet",
    "BassClarinet",
    "Flute",
    "Trombone",
    "Violin",
    "Oboe",
    "Bassoon",
    "Harp",
    "DoubleBass",
    "Clarinet",
    "Cello",
    "Tuba",
    "Percussion",
    "Viola",
    "Horn",
]

inst_mapping = {
    "Flute 2": "Flute",
    "Horn 4": "Horn",
    "Harp 1": "Harp",
    "Double bass Solo 1": "DoubleBass",
    "Cello solo 2": "Cello",
    "Oboe 1": "Oboe",
    "Bassoon 3": "Bassoon",
    "Trombone 1": "Trombone",
    "Bassoon 2": "Bassoon",
    "Horn 1": "Horn",
    "Flute 3": "Flute",
    "Trumpet 1": "Trumpet",
    "Double bass Tutti": "DoubleBass",
    "Double bass Solo": "DoubleBass",
    "Celli b": "Cello",
    "Violin I Tutti": "Violin",
    "Viola Tutti": "Viola",
    "Violins II Tutti": "Violin",
    "Clarinet Bass 1": "BassClarinet",
    "Violins IIb": "Violin",
    "Tuba 1": "Tuba",
    "Violin II solo 2": "Violin",
    "Bass Trb (Tuba MB)": "Tuba",
    "Viola Solo 1": "Viola",
    "Percussion 1": "Percussion",
    "Violin I solo": "Violin",
    "Piccolo 1": "Flute",
    "Violin I solo 1": "Violin",
    "Percussion 49": "Percussion",
    "Violin II solo": "Violin",
    "Timpani (Hn5 Full)": "Percussion",
    "Tuba 1 (Harp MB)": "Tuba",
    "Violins Ib": "Violin",
    "Celli Tutti": "Cello",
    "Clarinet 2 (Bb)": "Clarinet",
    "Tuba": "Tuba",
    "Violins I Tutti": "Violin",
    "Bass Clarinet (Cl3 MB)": "BassClarinet",
    "Viola Solo 2": "Viola",
    "Percussion 2": "Percussion",
    "Timpani 1": "Percussion",
    "Clarinet in Bb 1": "Clarinet",
    "Violin I solo 2": "Violin",
    "Bassoon Contra 1": "Bassoon",
    "Piccolo": "Flute",
    "Violin II Tutti": "Violin",
    "Flute Picc 1": "Flute",
    "Tuba 2": "Tuba",
    "Trombone Bass": "Trombone",
    "Viola b": "Viola",
    "Violin II solo 1": "Violin",
    "English Horn": "Horn",
    "Trombone 2": "Trombone",
    "Percussion 50": "Percussion",
    "Oboe 3": "Oboe",
    "Bassoon 1": "Bassoon",
    "Horn 2": "Horn",
    "Bass Clarinet": "BassClarinet",
    "Trumpet 2": "Trumpet",
    "Cello Tutti": "Cello",
    "Clarinet 1 (Bb)": "Clarinet",
    "Flute 1": "Flute",
    "Trumpet 3": "Trumpet",
    "Clarinet 3 (Bb)": "Clarinet",
    "Bass Trombone": "Trombone",
    "Harp 2": "Harp",
    "Cello solo 1": "Cello",
    "Trombone 3": "Trombone",
    "Oboe 2": "Oboe",
    "Contrabassoon": "DoubleBass",
    "Horn 3": "Horn",
}
